spring:
  application:
    name: spring-file-upload

  profiles:
    active: ${APP_PROFILE_ACTIVE:local}
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5433/jfswd_1_upload_file_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update

ps:
  app:
    api-url: http://localhost:8080


